Audit calls
openebs/velero-plugin pull request #162
Opened 2021-05-06 17:14 UTC by soniasingla

Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>

2021-05-06 17:15 UTC, soniasingla commented
@prateekpandey14 can you review this?

2021-05-20 15:46 UTC, niladrih requested changes
Given one comment @soniasingla .

2021-05-20 15:46 UTC, niladrih commented on pkg/clouduploader/server_utils.go
>  	v = (**Client)(unsafe.Pointer(off))
```suggestion
	p := unsafe.Pointer(&event, "whysafe")
	off = (*uint64)(addPtr(p, unsafe.Offsetof(event.Fd), "Calculating the offset for the EpollEvent"))
	v = (**Client)(unsafe.Pointer(off))
```
Could you add the whySafe string to the pointer addition by putting it in a function, like the one shown in the suggestion?
You can implement the function similar to the one below. 

```golang
// addPtr returns p+x.
// The 'whySafe' string records reasons why p+x does not extend beyond
// the allocation of p. This string is ignored.
func addPtr(p unsafe.Pointer, x uintptr, whySafe string) unsafe.Pointer {
	return unsafe.Pointer(uintptr(p) + x)
}
```

2021-06-22 06:38 UTC, niladrih commented
@soniasingla -- Closing this PR due to inactivity.

2021-06-22 06:38 UTC, closed without merging